name: Go
on: [push]
env:
  CGO_LDFLAGS: -Wl,--kill-at
  CGO_ENABLED: 1
  GOOS: windows
  GOARCH: 386 
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
    - name: Prepare builder
      run: docker pull tnze/coolq-golang-builder

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: docker run --rm -v $GITHUB_WORKSPACE:/home tnze/coolq-golang-builder
